/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d9dadb",
        "surface-variant": "#e1e3e4",
        "outline": "#727785",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "primary": "#005bbf",
        "inverse-primary": "#adc7ff",
        "surface-container": "#edeeef",
        "surface-container-low": "#f3f4f5",
        "on-secondary-container": "#fffbff",
        "surface-bright": "#f8f9fa",
        "on-primary-fixed-variant": "#004493",
        "primary-fixed-dim": "#adc7ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "secondary": "#4b41e1",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#e2dfff",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-container": "#645efb",
        "background": "#f8f9fa",
        "on-secondary-fixed": "#0f0069",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#d8e2ff",
        "inverse-surface": "#2e3132",
        "on-surface-variant": "#414754",
        "inverse-on-surface": "#f0f1f2",
        "secondary-fixed-dim": "#c3c0ff",
        "primary-container": "#1a73e8",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#001a41",
        "on-primary-container": "#ffffff",
        "on-surface": "#191c1d",
        "surface": "#f8f9fa",
        "on-tertiary-container": "#000703",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#002113",
        "surface-container-highest": "#e1e3e4",
        "tertiary-fixed": "#6ffbbe",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#005236",
        "on-background": "#191c1d",
        "on-secondary-fixed-variant": "#3323cc",
        "outline-variant": "#c1c6d6",
        "tertiary": "#006c49",
        "tertiary-container": "#00885d",
        "surface-tint": "#005bc0",
        "success-green": "#10B981",
        "trust-blue": "#1A73E8",
        "soft-amber": "#F59E0B"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "12px",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "margin-mobile": "20px",
        "unit": "4px",
        "gutter": "16px",
        "max-width": "480px"
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-bold": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-bold": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
